
import { Josefin_Sans } from "next/font/google";
import "@/app/_styles/globals.css"
import Header from "./_components/Header";
const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  display: "swap",
});
export const TITLE = "The Wild Oasis"
export const metadata = {
  title: {
    template: "%s / " + TITLE,
    default: TITLE
  },
  description: "Generated by Next.js",

};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${josefinSans.className} bg-primary-950 text-primary-100 min-h-screen flex flex-col relative`}>
        <Header />
        <div className="flex-1 px-8 py-12 grid">

          <main className="max-w-7xl mx-auto w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
